# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    tags:
        label: Tags
        type: group
        modelClass: Dipesh\Blog\Models\Tag
        nameFrom: title
        scope: applyTags
