list: $/dipesh/blog/models/team/columns.yaml
modelClass: Dipesh\Blog\Models\Team
title: Teams
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dipesh/blog/teams/update/:id'
