list: $/dipesh/blog/models/service/columns.yaml
modelClass: Dipesh\Blog\Models\Service
title: Services
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dipesh/blog/services/update/:id'
